### PR TITLE
Setup Webpack

### PR DESCRIPTION
**Pull request by austin-cavanagh**

### CODE REVIEW

**Review by DanaKaplan944 — COMMENTED** [review]
looks good

**Review by pwang040 — APPROVED** [review]

**Review by sung-kang — APPROVED** [review]
base

**Review by austin-cavanagh — COMMENTED** [review]
Good

**Review by pwang040 — APPROVED** [review]
all green

**Review by itsnancyhuang — APPROVED** [review]
good

**Review by sung-kang — APPROVED** [review]
base

**Review by pwang040 — APPROVED** [review]
plz work

**Review by sung-kang — APPROVED** [review]

**Review by pwang040 — APPROVED** [review]

**Pull request merged**
